server {
  listen 80;
  server_name _;

  location = / {
    return 302 /car_bbox_detector/;
  }

  location /car_bbox_detector/ {
    alias /usr/share/nginx/html/car_bbox_detector/;
    try_files $uri $uri/ /car_bbox_detector/index.html;
  }
}
