server {
  listen 80;
  server_name _;

  location = / {
    return 302 /client-side-object-detector/;
  }

  location /client-side-object-detector/ {
    alias /usr/share/nginx/html/client-side-object-detector/;
    try_files $uri $uri/ /client-side-object-detector/index.html;
  }
}
